# Generated by Django 3.0.8 on 2020-08-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20200806_0500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
